### ISSUE TITLE
errors in sensu-client.log

### ISSUE THREAD

**Issue by poxus** [sensu-plugins/sensu-plugins-nginx#2] opened 2015-06-23 16:20 UTC
hi! i have some errors in /var/log/sensu/sensu-client.log

"executed":1435076117,"duration":0.154,"output":"Check failed to run: undefined method `+' for nil:NilClass, [\"/usr/lib/ruby/2.1.0/net/http.rb:1529:in `addr_port'\", \"/usr/lib/ruby/2.1.0/net/http.rb:1462:in `begin_transport'\", \"/usr/lib/ruby/2.1.0/net/http.rb:1404:in `transport_request'\", \"/usr/lib/ruby/2.1.0/net/http.rb:1378:in `request'\", \"/etc/sensu/plugins/scp/nginx/nginx-metrics.rb:89:in `block in run'\", \"/usr/lib/ruby/2.1.0/net/http.rb:853:in `start'\", \"/usr/lib/ruby/2.1.0/net/http.rb:583:in `start'\", \"/etc/sensu/plugins/scp/nginx/nginx-metrics.rb:87:in `run'\", \"/var/lib/gems/2.1.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'\"]\n","status":2}}}

distr: debian_8
ruby version: ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

**Comment by poxus** [comment] 2015-06-24 10:30
hi again!
and i have some errors, when using ruby embedded:
"command":"/etc/sensu/plugins/nginx/nginx-metrics.rb","executed":1435141615,"duration":0.291,"output":"Check failed to run: undefined method `+' for nil:NilClass, [\"/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1533:in `addr_port'\", \"/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1466:in `begin_transport'\", \"/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1408:in `transport_request'\", \"/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:1382:in `request'\", \"/etc/sensu/plugins/nginx/nginx-metrics.rb:89:in `block in run'\", \"/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:852:in `start'\", \"/opt/sensu/embedded/lib/ruby/2.0.0/net/http.rb:582:in `start'\", \"/etc/sensu/plugins/nginx/nginx-metrics.rb:87:in `run'\", \"/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-plugin-1.1.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'\"]\n","status":2}}}

**Comment by rmalenko** [comment] 2015-09-21 18:25
I have got the same error

Check failed to run: undefined method `+' for nil:NilClass, ["/usr/lib/ruby/2.1.0/net/http.rb:1529:in `addr_port'", "/usr/lib/ruby/2.1.0/net/http.rb:1462:in `begin_transport'", "/usr/lib/ruby/2.1.0/net/http.rb:1404:in `transport_request'", "/usr/lib/ruby/2.1.0/net/http.rb:1378:in `request'", "/etc/sensu/plugins/nginx-metrics.rb:86:in `block in run'", "/usr/lib/ruby/2.1.0/net/http.rb:853:in `start'", "/usr/lib/ruby/2.1.0/net/http.rb:583:in `start'", "/etc/sensu/plugins/nginx-metrics.rb:84:in `run'", "/var/lib/gems/2.1.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]

**Comment by eheydrick** [comment] 2015-11-20 07:44
The problem is that there is no default hostname so you need to specify that. I think it should default to localhost if nothing is set. Will happily take a PR for that.

**Comment by eheydrick** [comment] 2015-12-02 01:42
Made the default hostname 'localhost'. Also added usage info.

**Comment by eheydrick** [comment] 2015-12-03 08:13
Fixed in version [1.0.0](https://rubygems.org/gems/sensu-plugins-nginx/versions/1.0.0).

**Closed by eheydrick** 2015-12-03 08:13 UTC
